stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: extras/docker/Dockerfile
      buildContext: .
      tag: fiware-idm
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      event:
        include:
        - push
  when:
    event: {}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: extras/docker/keyrock-deployment.yaml
  - applyYamlConfig:
      path: extras/docker/keyrock-service.yaml
timeout: 300
notification:
  recipients:
  - recipient: Ashima.Aggarwal@india.nec.com
    notifier: c-h8ztd:n-4927h
  condition:
  - Success
  - Changed
  - Failed
